# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000
  port: 5432
  username: postgres
  password: postgres   ### password you have specified within psql
  host: localhost

development:
  <<: *default
  database: stream_rails
  pool: 5


test:
  <<: *default
  database: stream_rails
  template: template0

production:
  <<: *default
  database: stream_rails